# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  schedule:
  - cron: "0 6 * * *"

name: update-data

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      ESAJ_LOGIN: ${{ secrets.ESAJLOGIN }}
      ESAJ_SENHA: ${{ secrets.ESAJSENHA }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: install deps
        run: sudo apt install libharfbuzz-dev libfribidi-dev libproj-dev libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev
      - name: Install dependencies
        run: |
          options(repos = c(pkgmanager = "https://packagemanager.rstudio.com/all/__linux__/bionic/2022-01-03+Y3JhbiwyOjQ1MjYyMTU7NTY4Qjk1ODA"))
          install.packages(c(
            "remotes", "rcmdcheck", "tidyverse", "progressr",
            "furrr", "writexl", "usethis"
          ))
          remotes::install_github("terranova/lex")
          remotes::install_local(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript "data-raw/update.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
