# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  schedule:
  - cron: "0 6 * * *"

name: update-data

jobs:
  uptade-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      ESAJ_LOGIN: ${{ secrets.ESAJLOGIN }}
      ESAJ_SENHA: ${{ secrets.ESAJSENHA }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::furrr
            any::remotes
            any::rcmdcheck
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Gcloud auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Atualizar dados
        run: Rscript data-raw/update.R
      - name: Upload DJs
        run: gsutil -m cp -r /inst/* gs://covid-tjsp
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/da_cjpg_covid.rda
          git add data/da_cpopg_covid.rda
          git commit -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
